// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team_3_BucHunt_WebApp.Models;

#nullable disable

namespace Team3BucHuntWebApp.Migrations
{
    [DbContext(typeof(BucHuntContext))]
    partial class BucHuntContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HuntLocation", b =>
                {
                    b.Property<int>("HuntId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("HuntId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("HuntLocation");
                });

            modelBuilder.Entity("HuntUser", b =>
                {
                    b.Property<int>("HuntId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HuntId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("HuntUser");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.Hunt", b =>
                {
                    b.Property<int>("HuntId")
                        .HasColumnType("int")
                        .HasColumnName("HuntID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("TeamGame")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("URL");

                    b.HasKey("HuntId");

                    b.ToTable("Hunts");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.HuntCode", b =>
                {
                    b.Property<int>("HuntId")
                        .HasColumnType("int")
                        .HasColumnName("HuntID");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int?>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("HuntId", "Code")
                        .HasName("PK_HuntCode");

                    b.ToTable("HuntCodes");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.QRCodeModel", b =>
                {
                    b.Property<string>("QRCodeText")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QRCodeText");

                    b.ToTable("QRCodeModel");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("TaskID");

                    b.Property<string>("Answer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("Question")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("HuntId")
                        .HasColumnType("int")
                        .HasColumnName("HuntID");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("UserId");

                    b.HasIndex("HuntId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HuntLocation", b =>
                {
                    b.HasOne("Team_3_BucHunt_WebApp.Models.Hunt", null)
                        .WithMany()
                        .HasForeignKey("HuntId")
                        .IsRequired()
                        .HasConstraintName("FK_HuntLocations_Hunts");

                    b.HasOne("Team_3_BucHunt_WebApp.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_HuntLocations_Locations");
                });

            modelBuilder.Entity("HuntUser", b =>
                {
                    b.HasOne("Team_3_BucHunt_WebApp.Models.Hunt", null)
                        .WithMany()
                        .HasForeignKey("HuntId")
                        .IsRequired()
                        .HasConstraintName("FK_HuntUsers_Hunts");

                    b.HasOne("Team_3_BucHunt_WebApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_HuntUsers_Users");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.HuntCode", b =>
                {
                    b.HasOne("Team_3_BucHunt_WebApp.Models.Hunt", "Hunt")
                        .WithMany("HuntCodes")
                        .HasForeignKey("HuntId")
                        .IsRequired()
                        .HasConstraintName("FK_HuntCodes_Hunts");

                    b.Navigation("Hunt");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.User", b =>
                {
                    b.HasOne("Team_3_BucHunt_WebApp.Models.Hunt", "Hunt")
                        .WithMany("UsersNavigation")
                        .HasForeignKey("HuntId")
                        .HasConstraintName("FK_Users_Hunts");

                    b.Navigation("Hunt");
                });

            modelBuilder.Entity("Team_3_BucHunt_WebApp.Models.Hunt", b =>
                {
                    b.Navigation("HuntCodes");

                    b.Navigation("UsersNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
